/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author The_S
 */
public class Menu extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.Conecta();

    public Menu() {
        initComponents();
        //Fecha
        Date sistFecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MMM/YYYY");
        menuFecha.setText(" Fecha: " + formato.format(sistFecha));
        //Hora
        Timer tiempo = new Timer(100, (ActionListener) new Menu.horas());
        tiempo.start();
    }

    class horas implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            java.util.Date sistHora = new java.util.Date();
            String pmAm = "hh:mm a";
            SimpleDateFormat format = new SimpleDateFormat(pmAm);
            Calendar hoy = Calendar.getInstance();
            menuHora.setText(" Hora: " + String.format(format.format(sistHora), hoy));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedorBotones = new javax.swing.JPanel();
        btnListaUsuarios = new javax.swing.JButton();
        btnFlujosTarea = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHora = new javax.swing.JMenu();
        menuFecha = new javax.swing.JMenu();
        codigoAutorizacionMenuTag = new javax.swing.JMenu();
        contactoMenuTag = new javax.swing.JMenu();
        fonoMenuTag = new javax.swing.JMenu();
        idUsuarioMenuTag = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(58, 175, 169));

        contenedorBotones.setBackground(new java.awt.Color(43, 122, 120));
        contenedorBotones.setLayout(new java.awt.GridLayout(3, 1, 40, 20));

        btnListaUsuarios.setBackground(new java.awt.Color(102, 102, 102));
        btnListaUsuarios.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        btnListaUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        btnListaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portafolio/imagenes/multiple-users-silhouette(3).png"))); // NOI18N
        btnListaUsuarios.setText("Usuarios");
        btnListaUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaUsuariosMouseExited(evt);
            }
        });
        btnListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaUsuariosActionPerformed(evt);
            }
        });
        contenedorBotones.add(btnListaUsuarios);

        btnFlujosTarea.setBackground(new java.awt.Color(102, 102, 102));
        btnFlujosTarea.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        btnFlujosTarea.setForeground(new java.awt.Color(204, 204, 204));
        btnFlujosTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portafolio/imagenes/list(2).png"))); // NOI18N
        btnFlujosTarea.setText("Flujo de tarea ");
        btnFlujosTarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnFlujosTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFlujosTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFlujosTareaMouseExited(evt);
            }
        });
        btnFlujosTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlujosTareaActionPerformed(evt);
            }
        });
        contenedorBotones.add(btnFlujosTarea);

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portafolio/imagenes/logout.png"))); // NOI18N
        btnSalir.setText("Salir ");
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        contenedorBotones.add(btnSalir);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(contenedorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        menuHora.setText(" Hora: ");
        menuHora.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jMenuBar1.add(menuHora);

        menuFecha.setText(" Fecha: ");
        menuFecha.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jMenuBar1.add(menuFecha);

        codigoAutorizacionMenuTag.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jMenuBar1.add(codigoAutorizacionMenuTag);

        contactoMenuTag.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jMenuBar1.add(contactoMenuTag);

        fonoMenuTag.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jMenuBar1.add(fonoMenuTag);

        idUsuarioMenuTag.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jMenuBar1.add(idUsuarioMenuTag);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUsuariosActionPerformed
        MantenedorUsuarios mantenedor = new MantenedorUsuarios();
        mantenedor.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnListaUsuariosActionPerformed

    private void btnFlujosTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlujosTareaActionPerformed
        FlujosPendientes flujos = new FlujosPendientes();
        flujos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlujosTareaActionPerformed

    private void btnListaUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaUsuariosMouseEntered
        btnListaUsuarios.setBackground(new Color(32, 140, 204));
    }//GEN-LAST:event_btnListaUsuariosMouseEntered

    private void btnListaUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaUsuariosMouseExited
        btnListaUsuarios.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnListaUsuariosMouseExited

    private void btnFlujosTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlujosTareaMouseEntered
        btnFlujosTarea.setBackground(new Color(32, 140, 204));
    }//GEN-LAST:event_btnFlujosTareaMouseEntered

    private void btnFlujosTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlujosTareaMouseExited
        btnFlujosTarea.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnFlujosTareaMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(32, 140, 204));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlujosTarea;
    private javax.swing.JButton btnListaUsuarios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu codigoAutorizacionMenuTag;
    private javax.swing.JMenu contactoMenuTag;
    private javax.swing.JPanel contenedorBotones;
    private javax.swing.JMenu fonoMenuTag;
    private javax.swing.JMenu idUsuarioMenuTag;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuFecha;
    private javax.swing.JMenu menuHora;
    // End of variables declaration//GEN-END:variables
}
